ballerina-platform/module-ballerina-xmldata

- .github/workflows/build-master.yml
- README.md
- xmlutils-ballerina/build.gradle
> Update readme file

- xmlutils-ballerina/src/xmlutils/tests/xmlutils_test.bal
- xmlutils-ballerina/src/xmlutils/xmlutils.bal
> Add Ballerina class support

- xmlutils-native/src/main/java/org/ballerinalang/stdlib/xmlutils/ConvertUtils.java
- xmlutils-native/src/main/java/org/ballerinalang/stdlib/xmlutils/JSONToXMLConverter.java
> Migrate jBallerina Runtime APIs

- .github/workflows/pull-request.yml
- xmlutils-ballerina/src/xmlutils/xmlutils.bal
> Update with isolated function changes

- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- build.gradle
- xmlutils-ballerina/build.gradle
> Update the release workflow

- build.gradle
- gradle.properties
- xmlutils-native/build.gradle
> Enable Spotbugs and checkstyle tasks

- xmlutils-native/src/main/java/module-info.java
- xmlutils-native/src/main/java/org/ballerinalang/stdlib/xmlutils/ConvertUtils.java
- xmlutils-native/src/main/java/org/ballerinalang/stdlib/xmlutils/JSONToXMLConverter.java
Refactor ballerina runtime api usages
> Migrate ballerina runtime apis

- gradle.properties
> Update ballerina-lang  version

- xmlutils-ballerina/build.gradle
> Update ballerina command to bal command
> Update ballerina command to bal command

- xmlutils-ballerina/xmlutils.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Change the name of the `java` langlib module to `jballerina.java`

- .github/workflows/build-master.yml
- .github/workflows/pull-request.yml
- xmlutils-ballerina/build.gradle
> Generate code coverage report

- xmlutils-ballerina/build.gradle
> Add native dependency

- xmlutils-ballerina/build.gradle
> Make changes in the bulid gradle

- xmlutils-ballerina/build.gradle
> Avoid running tests twice when publishing

- xmlutils-ballerina/build.gradle
> Renames the extension of the package distribution file from balo to bala 
> Fixes ballerina-platform/ballerina-lang#28476
> Replace balo with bala

- README.md
- xmlutils-ballerina/Package.md
> Change module to package

- .github/workflows/publish-release.yml
- build.gradle
- gradle.properties
- xmlutils-ballerina/build.gradle
> Enable Publishing to Ballerina Central on Release

- build.gradle
- xmlutils-ballerina/build.gradle
> Re-order build tasks to enable publishing to central

- .github/workflows/build-master.yml
- .github/workflows/pull-request.yml
- xmldata-ballerina/build.gradle
> Remove publishing testable jar and exec artifacts

- xmldata-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
> Add extracted bala in the zip artifact

- xmldata-ballerina/build.gradle
> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032
> Add -c flag to build command

- .github/workflows/build-master.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- README.md
- xmldata-ballerina/Ballerina.toml
- xmldata-ballerina/init.bal
- xmldata-native/build.gradle
- xmldata-native/src/main/java/org/ballerinalang/stdlib/xmldata/XmlToJson.java
$Subject
Related issue: [#69](https://github.com/ballerina-platform/module-ballerina-xmldata/pull/69)
> Change xmlutils  keywords to xmldata

- .github/workflows/central-publish.yml
> Add workflow to publish package to central

- build.gradle
- xmldata-ballerina/build.gradle
> Strip stdlib dependency version

- .github/workflows/central-publish.yml
- README.md
- xmldata-ballerina/build.gradle
$Subject
Related issue: [#1247](https://github.com/ballerina-platform/ballerina-standard-library/issues/1247)
-dab819c1` and relevant extensions.
> Fix the Ballerina.toml updating before the Ballerina push

- build-config/checkstyle/build.gradle
- build.gradle
- gradle.properties
- xmldata-ballerina/build.gradle
Standardize build script of Ballerina module
> Apply Gradle Ballerina plugin for Ballerina module build script

- README.md
- xmldata-ballerina/Module.md
- xmldata-ballerina/Package.md
- xmldata-ballerina/xmldata.bal
> Improve API Docs

- gradle.properties
- xmldata-ballerina/build.gradle
> Bump ballerina plugin version

- xmldata-ballerina/build.gradle
Remove overriding testCoverageParam and use the value from the gradle plugin.
> Remove overriding testCoverageParam

- README.md
- xmldata-ballerina/Module.md
- xmldata-native/src/main/java/org/ballerinalang/stdlib/xmldata/JsonToXml.java
> Remove inconsistencies when referring to `xml`

- README.md
- xmldata-ballerina/Module.md
- xmldata-ballerina/Package.md
- xmldata-ballerina/xmldata.bal
> Remove backticks from xml and json keywords

- xmldata-ballerina/Package.md
$Subject
Related issue: ballerina-platform/ballerina-standard-library#1462
> Update Package.md links into HTML format

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
$Subject
Related issue:ballerina-platform/ballerina-release#547
> Update GitHub action workflow scripts

- gradle.properties
$Subject
Related: [#1334](https://github.com/ballerina-platform/ballerina-standard-library/issues/1334)
> Remove Pre-Release Tag from the Version

- .github/workflows/build-timestamped-master.yml
- ballerina/Dependencies.toml
https://github.com/ballerina-platform/ballerina-standard-library/issues/2362
> Skip master build for .md file changes

- ballerina/tests/xml_to_json_test.bal
- ballerina/tests/xml_to_record_test.bal
- ballerina/xmldata.bal
- changelog.md
- gradle.properties
- native/build.gradle
- native/src/main/java/io/ballerina/stdlib/xmldata/XmlToJson.java
- native/src/main/java/io/ballerina/stdlib/xmldata/XmlToRecord.java
- native/src/main/java/io/ballerina/stdlib/xmldata/utils/Constants.java
- native/src/main/java/module-info.java
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2406
> Implement toRecord function

- ballerina/Ballerina.toml
- build-config/resources/Ballerina.toml
$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2478
> Update distribution and module versions

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- ballerina/tests/xml_from_json_test.bal
- ballerina/tests/xml_to_record_test.bal
- ballerina/xmldata.bal
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2336
> Improve code quality

- .gitignore
- ballerina/tests/xml_from_json_test.bal
- ballerina/xmldata.bal
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2506
> Fix bug when JSON is a single value

- ballerina/Module.md
- ballerina/Package.md
- ballerina/xmldata.bal
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2591
> Improve xmldata module API docs

- docs/spec/spec.md
$Subject
Fixes:  https://github.com/ballerina-platform/ballerina-standard-library/issues/2647
> Update the specification

- native/src/main/java/io/ballerina/stdlib/xmldata/XmlToJson.java
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2568
> Remove deprecated method usage

- ballerina/xmldata.bal
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2925
> Update fromJson() API doc

- ballerina/Dependencies.toml
- docs/spec/spec.md
> Reformat the spec

- docs/spec/spec.md
> Update the content and sub-heading style

- gradle.properties
- native/src/main/java/io/ballerina/stdlib/xmldata/XmlToJson.java
> Update the impl of getting field type with the latest changes

- ballerina/Dependencies.toml
- docs/proposals/toXml_fromXml_apis.md
$Subject 
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2819
> Add proposal to introduce `toXml` and `fromXml` APIs

- gradle.properties
- native/src/main/java/io/ballerina/stdlib/xmldata/XmlToJson.java
> Fix the build failure with the latest lang changes

- ballerina/tests/to_xml_test.bal
- ballerina/xmldata.bal
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3103
> Fix an issue that gets during the namespace prefix is empty

- ballerina/Dependencies.toml
- ballerina/tests/to_xml_test.bal
- native/src/main/java/io/ballerina/stdlib/xmldata/utils/XmlDataUtils.java
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3106
> Fix an error when the first field type of the record is an array

- ballerina/Ballerina.toml
- build-config/resources/Ballerina.toml
- gradle.properties
$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3128
> Update distribution and lang vesion

- .github/workflows/update_specs.yml
- docs/spec/spec.md
$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3154
> Add workflow to update specs and update the conversion rule in spec

- docs/spec/spec.md
- gradle.properties
> Change the spec headings font size

- ballerina/Dependencies.toml
- ballerina/tests/to_xml_test.bal
- ballerina/xmldata.bal
- changelog.md
- docs/spec/spec.md
- native/src/main/java/io/ballerina/stdlib/xmldata/utils/Constants.java
- native/src/main/java/io/ballerina/stdlib/xmldata/utils/XmlDataUtils.java
$Subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/3713 
https://github.com/ballerina-platform/ballerina-standard-library/issues/3716
> Fix issues in `toXml` API and update the docs

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
> Update lang timestamped and distribution versions

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/tests/from_xml_test.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/xmldata/XmlToJson.java
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4155
> Fix issue when the XML element has no content

- ballerina/tests/from_xml_test.bal
- ballerina/xmldata.bal
- native/src/main/java/io/ballerina/stdlib/xmldata/XmlToJson.java
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4036
> Validate the uri of the namespace

- .github/workflows/build-with-bal-test-native.yml
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4142
> Add GraalVM check for the pull requests

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/xmldata/MapFromXml.java
- native/src/main/java/io/ballerina/stdlib/xmldata/XmlToRecord.java
Partially fixes the issue https://github.com/ballerina-platform/ballerina-standard-library/issues/3933
> Use convert API instead of `CloneWithType`

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
Reverts ballerina-platform/module-ballerina-xmldata#495
> Revert "Update lang version"

- ballerina/Ballerina.toml
> [Automated] Update native jar versions in toml files

- README.md
- ballerina/Dependencies.toml
- gradle.properties
> Java17 migration

- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/xmldata/compiler/CompilerPluginTest.java
- compiler-plugin-tests/src/test/resources/diagnostics/sample11/main.bal
- compiler-plugin-tests/src/test/resources/diagnostics/sample12/Ballerina.toml
- compiler-plugin-tests/src/test/resources/diagnostics/sample12/main.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/xmldata/compiler/XmldataRecordFieldValidator.java
> Fix NPE from the compiler plugin

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/tests/from_xml_test.bal
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/xmldata/compiler/CompilerPluginTest.java
- compiler-plugin-tests/src/test/resources/diagnostics/sample11/Ballerina.toml
- compiler-plugin-tests/src/test/resources/diagnostics/sample11/main.bal
- compiler-plugin-tests/src/test/resources/diagnostics/sample12/Ballerina.toml
- compiler-plugin-tests/src/test/resources/diagnostics/sample12/main.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/xmldata/compiler/DiagnosticsCodes.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/xmldata/compiler/XmldataCodeAnalyzer.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/xmldata/compiler/XmldataRecordFieldValidator.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/xmldata/compiler/object/Record.java
- native/src/main/java/io/ballerina/stdlib/xmldata/MapFromXml.java
- native/src/main/java/io/ballerina/stdlib/xmldata/XmlToJson.java
- native/src/main/java/io/ballerina/stdlib/xmldata/utils/Constants.java
- native/src/main/java/io/ballerina/stdlib/xmldata/utils/FieldDetails.java
- native/src/main/java/io/ballerina/stdlib/xmldata/utils/XmlDataUtils.java
$Subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/3802
> Fix mismatch error

- ballerina/tests/from_xml_test.bal
- ballerina/xmldata.bal
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/xmldata/compiler/CompilerPluginTest.java
- compiler-plugin-tests/src/test/resources/diagnostics/sample11/main.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/xmldata/compiler/DiagnosticsCodes.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/xmldata/compiler/XmldataRecordFieldValidator.java
> Change compiler plugin error for child node name annotation to warning 

- gradle.properties
Reverts ballerina-platform/module-ballerina-xmldata#536
> Revert "[AUTO MERGE] Update Dependencies (Ballerina Lang : 2201.9.0-20240419-152500-bd530dd2)"

- .github/workflows/build-timestamped-master.yml
- .github/workflows/build-with-bal-test-graalvm.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
> Update workflows ballerina-library

- .github/workflows/build-timestamped-master.yml
- .github/workflows/build-with-bal-test-graalvm.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- README.md
- ballerina/Ballerina.toml
- build-config/resources/Ballerina.toml
- compiler-plugin-tests/build.gradle
- compiler-plugin/build.gradle
- gradle.properties
- native/build.gradle
> Migrate to Java 21

- build-config/resources/Ballerina.toml
- gradle.properties
> Update dependency versions for Update 11

- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/trivy-scan.yml
> update the workflow
